/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = DIGIT_BITS
     DIV = DIV
     TOP = DIGITS-1
     UP = 1
*/
module counter_5 (
    input clk,
    input rst,
    output reg [3:0] value
  );
  
  localparam SIZE = 3'h4;
  localparam DIV = 4'h8;
  localparam TOP = 6'h0f;
  localparam UP = 1'h1;
  
  
  reg [11:0] M_ctr_d, M_ctr_q = 1'h0;
  
  localparam MAX_VALUE = 14'h0fff;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    value = M_ctr_q[8+3-:4];
    if (1'h1) begin
      M_ctr_d = M_ctr_q + 1'h1;
      if (1'h1 && M_ctr_q == 14'h0fff) begin
        M_ctr_d = 1'h0;
      end
    end else begin
      M_ctr_d = M_ctr_q - 1'h1;
      if (1'h1 && M_ctr_q == 1'h0) begin
        M_ctr_d = 14'h0fff;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
