/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module pseudorandomnumber_3 (
    input clk,
    input rst,
    output reg [63:0] sixteen
  );
  
  
  
  wire [32-1:0] M_pn_gen1_num;
  reg [1-1:0] M_pn_gen1_next;
  reg [32-1:0] M_pn_gen1_seed;
  pn_gen_8 pn_gen1 (
    .clk(clk),
    .rst(rst),
    .next(M_pn_gen1_next),
    .seed(M_pn_gen1_seed),
    .num(M_pn_gen1_num)
  );
  
  wire [32-1:0] M_pn_gen2_num;
  reg [1-1:0] M_pn_gen2_next;
  reg [32-1:0] M_pn_gen2_seed;
  pn_gen_8 pn_gen2 (
    .clk(clk),
    .rst(rst),
    .next(M_pn_gen2_next),
    .seed(M_pn_gen2_seed),
    .num(M_pn_gen2_num)
  );
  
  reg [31:0] M_seed1_d, M_seed1_q = 1'h0;
  
  reg [31:0] M_seed2_d, M_seed2_q = 1'h0;
  
  always @* begin
    M_seed2_d = M_seed2_q;
    M_seed1_d = M_seed1_q;
    
    M_pn_gen1_seed = M_seed1_q;
    M_pn_gen1_next = 1'h0;
    M_pn_gen2_seed = M_seed2_q;
    M_pn_gen2_next = 1'h0;
    if (rst) begin
      M_seed1_d = M_seed1_q + 1'h1;
      M_seed2_d = M_seed2_q + 2'h2;
    end
    sixteen = {M_pn_gen1_num[0+3-:4], M_pn_gen1_num[4+3-:4], M_pn_gen1_num[8+3-:4], M_pn_gen1_num[12+3-:4], M_pn_gen1_num[16+3-:4], M_pn_gen1_num[20+3-:4], M_pn_gen1_num[24+3-:4], M_pn_gen1_num[28+3-:4], M_pn_gen2_num[0+3-:4], M_pn_gen2_num[4+3-:4], M_pn_gen2_num[8+3-:4], M_pn_gen2_num[12+3-:4], M_pn_gen2_num[16+3-:4], M_pn_gen2_num[20+3-:4], M_pn_gen2_num[24+3-:4], M_pn_gen2_num[28+3-:4]};
  end
  
  always @(posedge clk) begin
    M_seed2_q <= M_seed2_d;
  end
  
  
  always @(posedge clk) begin
    M_seed1_q <= M_seed1_d;
  end
  
endmodule
