/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    input buttonup,
    input buttondown,
    input buttonleft,
    input buttonright,
    output reg [7:0] io_seg,
    output reg [15:0] io_sel,
    output reg [3:0] st_sel,
    output reg [7:0] st_seg
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [8-1:0] M_seg_seg;
  wire [16-1:0] M_seg_sel;
  reg [80-1:0] M_seg_values;
  multi_seven_seg_2 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  wire [64-1:0] M_pseudorandomnumber_sixteen;
  pseudorandomnumber_3 pseudorandomnumber (
    .clk(clk),
    .rst(rst),
    .sixteen(M_pseudorandomnumber_sixteen)
  );
  wire [80-1:0] M_addgame_segment_display;
  wire [5-1:0] M_addgame_current;
  wire [20-1:0] M_addgame_steps;
  reg [80-1:0] M_addgame_sixteen;
  addgame_4 addgame (
    .clk(clk),
    .rst(rst),
    .buttondown(buttondown),
    .buttonup(buttonup),
    .buttonleft(buttonleft),
    .buttonright(buttonright),
    .sixteen(M_addgame_sixteen),
    .segment_display(M_addgame_segment_display),
    .current(M_addgame_current),
    .steps(M_addgame_steps)
  );
  wire [8-1:0] M_step_seg_seg;
  wire [4-1:0] M_step_seg_sel;
  reg [20-1:0] M_step_seg_values;
  multi_seven_seg_5 step_seg (
    .clk(clk),
    .rst(rst),
    .values(M_step_seg_values),
    .seg(M_step_seg_seg),
    .sel(M_step_seg_sel)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    led = 8'h00;
    M_addgame_sixteen = 80'h08421084210842108421;
    M_seg_values = M_addgame_segment_display;
    M_seg_values[(M_addgame_current)*5+4-:5] = M_addgame_segment_display[(M_addgame_current)*5+4-:5] + 5'h10;
    io_seg = ~M_seg_seg;
    io_sel = ~M_seg_sel;
    M_step_seg_values = M_addgame_steps;
    st_seg = ~M_step_seg_seg;
    st_sel = ~M_step_seg_sel;
  end
endmodule
