/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_7 (
    input [4:0] char,
    output reg [7:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        segs = 8'hc0;
      end
      1'h1: begin
        segs = 8'hf9;
      end
      2'h2: begin
        segs = 8'ha4;
      end
      2'h3: begin
        segs = 8'hb0;
      end
      3'h4: begin
        segs = 8'h99;
      end
      3'h5: begin
        segs = 8'h92;
      end
      3'h6: begin
        segs = 8'h82;
      end
      3'h7: begin
        segs = 8'hf8;
      end
      4'h8: begin
        segs = 8'h80;
      end
      4'h9: begin
        segs = 8'h98;
      end
      4'ha: begin
        segs = 8'hc0;
      end
      4'hb: begin
        segs = 8'hf9;
      end
      4'hc: begin
        segs = 8'ha4;
      end
      4'hd: begin
        segs = 8'hb0;
      end
      4'he: begin
        segs = 8'h99;
      end
      4'hf: begin
        segs = 8'h92;
      end
      5'h10: begin
        segs = 8'h40;
      end
      5'h11: begin
        segs = 8'h79;
      end
      5'h12: begin
        segs = 8'h24;
      end
      5'h13: begin
        segs = 8'h30;
      end
      5'h14: begin
        segs = 8'h19;
      end
      5'h15: begin
        segs = 8'h12;
      end
      5'h16: begin
        segs = 8'h02;
      end
      5'h17: begin
        segs = 8'h78;
      end
      5'h18: begin
        segs = 8'h00;
      end
      5'h19: begin
        segs = 8'h18;
      end
      5'h1a: begin
        segs = 8'h40;
      end
      5'h1b: begin
        segs = 8'h79;
      end
      5'h1c: begin
        segs = 8'h24;
      end
      5'h1d: begin
        segs = 8'h30;
      end
      5'h1e: begin
        segs = 8'h19;
      end
      5'h1f: begin
        segs = 8'h12;
      end
      default: begin
        segs = 8'hff;
      end
    endcase
  end
endmodule
